import { Ausstattung, getItemIfNotZero } from ".";
import EquipType from "./equipType"
import { Skill, SKILL_LIST } from "./skills";

export type Stats = { 
	armor?: number;
    health?: number;
    dmg?: number;
    spd?: number;
	mArmor?: number;
    mDmg?: number;
	skill?: Skill[]
}

export type Item = { 
    id: number;
    goldCost: number;
    name?: string;
    equipType: EquipType;
    resourceName: string;
    isPatreon: boolean;
    isEventItem: boolean;
    aniName?: string;
    boldID?: number;
    aniNgme?: string;
    desc?: string;
} & Stats

export type InventoryItem = { 
	level: number;
} & Item

export function sumStats(equipment: Ausstattung | undefined) { 
	const summedStats : Stats = {
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
	};

	const stats = [
		equipment?.armor,
		equipment?.back, 
		equipment?.headFront,
        equipment?.headHair, 
		equipment?.headTop,
        equipment?.lWeapon, 
		equipment?.rWeapon, 
		equipment?.shoes, 
	]

	const inventoryItemsStats = stats
		.map(x => equipment?.itemIDList
			.find(y => y.id === x))
		.filter(x => x !== undefined);

	for (const stat of inventoryItemsStats) {
		summedStats.armor! +=  stat.armor ?? 0
		summedStats.health! += stat.health ?? 0;
		summedStats.dmg! += stat.dmg ?? 0;
		summedStats.spd! += (stat.spd ?? 0) * -1;
		summedStats.mArmor! += stat.mArmor ?? 0;
		summedStats.mDmg! += stat.mDmg ?? 0;
	}

	return summedStats;
}

export const ITEMS: Item[] = 
[ 
	{
		id: 0,
		goldCost: 0,
		name: "male",
		resourceName: "Male",
		equipType: EquipType.Gender,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 1,
		goldCost: 0,
		name: "female",
		resourceName: "Female",
		equipType: EquipType.Gender,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 2,
		goldCost: 100,
		name: "dagger01_blue",
		resourceName: "skins\\04 Attach Weapons\\Daggers (R Arm)\\Dagger 01 Blue",
		equipType: EquipType.Weapon_R,
		aniName: "Melee Right Attack 01",
		armor: 0,
		health: 0,
		dmg: 5,
		spd: -0.25,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 3,
		goldCost: 150,
		name: "thieve_black",
		resourceName: "Male White Archer 01 Black",
		equipType: EquipType.Armor,
		armor: 3,
		health: 10,
		dmg: 0,
		spd: -0.05,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 4,
		goldCost: 110,
		name: "hat01_red",
		resourceName: "skins\\03 Attach Accessories\\Hats (Head)\\Hat 02 Peasant Grey Red",
		equipType: EquipType.HeadTop,
		armor: 2,
		health: 4,
		dmg: 0,
		spd: 0,
		mArmor: 1,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 5,
		goldCost: 140,
		name: "face01_normal",
		resourceName: "skins\\03 Attach Accessories\\Horns (Head)\\Horn 01 Front White",
		equipType: EquipType.HeadFront,
		armor: 1,
		health: 6,
		dmg: 2,
		spd: 0,
		mArmor: 1,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 6,
		goldCost: 200,
		name: "face01_red",
		resourceName: "skins\\03 Attach Accessories\\Horns (Head)\\Horn 01 Front Red",
		equipType: EquipType.HeadFront,
		armor: 2,
		health: 6,
		dmg: 2,
		spd: 0,
		mArmor: 1,
		mDmg: 4,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 7,
		goldCost: 200,
		name: "face01_black",
		resourceName: "skins\\03 Attach Accessories\\Horns (Head)\\Horn 01 Front Black",
		equipType: EquipType.HeadFront,
		armor: 2,
		health: 6,
		dmg: 6,
		spd: 0,
		mArmor: 1,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 8,
		goldCost: 135,
		name: "longbow_black",
		resourceName: "skins\\04 Attach Weapons\\Longbows (L Arm)\\Longbow 01 Black",
		equipType: EquipType.Bow,
		aniName: "Longbow Shoot Attack 01",
		armor: 0,
		health: 0,
		dmg: 3,
		spd: 0.5,
		mArmor: 0,
		boldID: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 9,
		goldCost: 125,
		name: "headband01",
		resourceName: "skins\\03 Attach Accessories\\Headbands (Head)\\Headband 01 Black White",
		equipType: EquipType.HeadTop,
		armor: 3,
		health: 0,
		dmg: 1,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 10,
		goldCost: 125,
		name: "headband02",
		resourceName: "skins\\03 Attach Accessories\\Headbands (Head)\\Headband 01 Black Yellow",
		equipType: EquipType.HeadTop,
		armor: 3,
		health: 0,
		dmg: 1,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 11,
		goldCost: 155,
		name: "headband03",
		resourceName: "skins\\03 Attach Accessories\\Headbands (Head)\\Headband 04 Blue",
		equipType: EquipType.HeadTop,
		armor: 0,
		health: 10,
		dmg: 0,
		spd: -0.1,
		mArmor: 2,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 12,
		goldCost: 275,
		name: "headband04",
		resourceName: "skins\\03 Attach Accessories\\Headbands (Head)\\Headband 03 Green",
		equipType: EquipType.HeadTop,
		armor: 2,
		health: 5,
		dmg: 0,
		spd: 0,
		mArmor: 2,
		mDmg: 0,
		skill: [ SKILL_LIST[0]  ],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 13,
		goldCost: 260,
		name: "headband05",
		resourceName: "skins\\03 Attach Accessories\\Headbands (Head)\\Headband 03 Red",
		equipType: EquipType.HeadTop,
		armor: 0,
		health: 0,
		dmg: 3,
		spd: -0.15,
		mArmor: 0,
		mDmg: 0,
		skill: [ SKILL_LIST[1]  ],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 14,
		goldCost: 50,
		name: "hair01",
		resourceName: "skins\\02 Attach Hair\\Male\\Hair Male 01 Black",
		equipType: EquipType.Hair,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 15,
		goldCost: 50,
		name: "hair02",
		resourceName: "skins\\02 Attach Hair\\Male\\Hair Male 01 Blonde",
		equipType: EquipType.Hair,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 16,
		goldCost: 50,
		name: "hair03",
		resourceName: "skins\\02 Attach Hair\\Male\\Hair Male 01 Brown",
		equipType: EquipType.Hair,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 17,
		goldCost: 50,
		name: "hair04",
		resourceName: "skins\\02 Attach Hair\\Female\\Hair Female 01 Cyan",
		equipType: EquipType.Hair,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 18,
		goldCost: 50,
		name: "hair05",
		resourceName: "skins\\02 Attach Hair\\Male\\Hair Male 01 Purple",
		equipType: EquipType.Hair,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 19,
		goldCost: 50,
		name: "hair06",
		resourceName: "skins\\02 Attach Hair\\Male\\Hair Male 01 Red",
		equipType: EquipType.Hair,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 20,
		goldCost: 50,
		name: "hair07",
		resourceName: "skins\\02 Attach Hair\\Male\\Hair Male 01 White",
		equipType: EquipType.Hair,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 21,
		goldCost: 145,
		name: "wand01",
		resourceName: "skins\\04 Attach Weapons\\Wands (R Arm)\\Wand 01 Stick Blue",
		equipType: EquipType.Wand,
		aniName: "Projectile Right Attack 01",
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 5,
		boldID: 1,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 22,
		goldCost: 0,
		name: "skin_white",
		resourceName: "White",
		equipType: EquipType.SkinColor,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 23,
		goldCost: 0,
		name: "skin_brown",
		resourceName: "Brown",
		equipType: EquipType.SkinColor,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 24,
		goldCost: 0,
		name: "skin_black",
		resourceName: "Black",
		equipType: EquipType.SkinColor,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 25,
		goldCost: 150,
		name: "knight01",
		resourceName: "Male White Knight 01 Black",
		equipType: EquipType.Armor,
		armor: 6,
		health: 0,
		dmg: 0,
		spd: 0.05,
		mArmor: 1,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 26,
		goldCost: 150,
		name: "barbarian01",
		resourceName: "Male White Barbarian 01 Blue",
		equipType: EquipType.Armor,
		armor: 0,
		health: 12,
		dmg: 1,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 27,
		goldCost: 150,
		name: "robe01",
		resourceName: "Male White L Robe 01 Blue",
		equipType: EquipType.Armor,
		armor: 0,
		health: 2,
		dmg: 0,
		spd: 0,
		mArmor: 7,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 28,
		goldCost: 170,
		name: "shield01",
		resourceName: "skins\\04 Attach Weapons\\Shields (L Arm)\\Shield 01 Black",
		equipType: EquipType.Shield,
		armor: 5,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 29,
		goldCost: 175,
		name: "eh_sword",
		resourceName: "skins\\04 Attach Weapons\\Swords (R Arm)\\Sword 01 Black",
		equipType: EquipType.Weapon_R,
		aniName: "Melee Right Attack 03",
		armor: 0,
		health: 0,
		dmg: 9,
		spd: 0.15,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 30,
		goldCost: 100,
		name: "shoes01",
		resourceName: "equip\\schuhe01\\Schuh01",
		equipType: EquipType.Shoes,
		armor: 2,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 1,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 31,
		goldCost: 6666666,
		name: "hair08",
		resourceName: "skins\\02 Attach Hair\\Male\\Hair Male 17 Fire",
		equipType: EquipType.Hair,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 32,
		goldCost: 320,
		name: "eh_sword01",
		resourceName: "skins\\04 Attach Weapons\\Swords (R Arm)\\Sword 02 Normal",
		equipType: EquipType.Weapon_R,
		aniName: "Melee Right Attack 03",
		armor: 0,
		health: 0,
		dmg: 15,
		spd: 0.17,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 33,
		goldCost: 360,
		name: "eh_sword02",
		resourceName: "skins\\04 Attach Weapons\\Swords (R Arm)\\Sword 02 Poison",
		equipType: EquipType.Weapon_R,
		aniName: "Melee Right Attack 03",
		armor: 0,
		health: 0,
		dmg: 12,
		spd: 0.2,
		mArmor: 0,
		mDmg: 0,
		skill: [ SKILL_LIST[2]  ],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 34,
		goldCost: 360,
		name: "eh_sword03",
		resourceName: "skins\\04 Attach Weapons\\Swords (R Arm)\\Sword 02 Ice",
		equipType: EquipType.Weapon_R,
		aniName: "Melee Right Attack 03",
		armor: 0,
		health: 0,
		dmg: 13,
		spd: 0.2,
		mArmor: 0,
		mDmg: 0,
		skill: [ SKILL_LIST[3]  ],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 35,
		goldCost: 420,
		name: "eh_sword04",
		resourceName: "skins\\04 Attach Weapons\\Swords (R Arm)\\Sword 02 Fire",
		equipType: EquipType.Weapon_R,
		aniName: "Melee Right Attack 03",
		armor: 0,
		health: 0,
		dmg: 9,
		spd: 0.17,
		mArmor: 0,
		mDmg: 0,
		skill: [ SKILL_LIST[4]  ],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 36,
		goldCost: 300,
		name: "longbow01",
		resourceName: "skins\\04 Attach Weapons\\Longbows (L Arm)\\Longbow 01 Blue",
		equipType: EquipType.Bow,
		aniName: "Longbow Shoot Attack 01",
		armor: 0,
		health: 0,
		dmg: 6,
		spd: 0.45,
		mArmor: 0,
		boldID: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 37,
		goldCost: 350,
		name: "longbow02",
		resourceName: "skins\\04 Attach Weapons\\Longbows (L Arm)\\Longbow 01 Green",
		equipType: EquipType.Bow,
		aniName: "Longbow Shoot Attack 01",
		armor: 0,
		health: 0,
		dmg: 5,
		spd: 0.55,
		mArmor: 0,
		mDmg: 0,
		boldID: 0,
		skill: [ SKILL_LIST[5]  ],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 38,
		goldCost: 380,
		name: "longbow03",
		resourceName: "skins\\04 Attach Weapons\\Longbows (L Arm)\\Longbow 01 Red",
		equipType: EquipType.Bow,
		aniName: "Longbow Shoot Attack 01",
		armor: 0,
		health: 0,
		dmg: 4,
		spd: 0.45,
		mArmor: 0,
		mDmg: 0,
		boldID: 0,
		skill: [ SKILL_LIST[6]  ],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 39,
		goldCost: 310,
		name: "wand02",
		resourceName: "skins\\04 Attach Weapons\\Wands (R Arm)\\Wand 03 Blue",
		equipType: EquipType.Wand,
		aniName: "Projectile Right Attack 01",
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 10,
		boldID: 1,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 40,
		goldCost: 480,
		name: "wand03",
		resourceName: "skins\\04 Attach Weapons\\Wands (R Arm)\\Wand 03 Red",
		equipType: EquipType.Wand,
		aniName: "CastSpell",
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 7,
		boldID: 2,
		skill: [
            SKILL_LIST[7],
            SKILL_LIST[8]
        ],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 41,
		goldCost: 450,
		name: "wand04",
		resourceName: "skins\\04 Attach Weapons\\Wands (R Arm)\\Wand 02 Green",
		equipType: EquipType.Wand,
		aniName: "Projectile Right Attack 01",
		armor: 0,
		health: 4,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 6,
		boldID: 3,
		skill: [ SKILL_LIST[9]  ],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 42,
		goldCost: 450,
		name: "wand05",
		resourceName: "skins\\04 Attach Weapons\\Wands (R Arm)\\Wand 02 Yellow",
		equipType: EquipType.Wand,
		aniName: "Projectile Right Attack 01",
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0.95,
		mArmor: 0,
		mDmg: 32,
		boldID: 4,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 43,
		goldCost: 335,
		name: "event_egg01",
		resourceName: "equip\\event\\EggHat",
		equipType: EquipType.HeadTop,
		armor: 6,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 6,
		mDmg: 0,
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 44,
		goldCost: 350,
		name: "shield02",
		resourceName: "skins\\04 Attach Weapons\\Shields (L Arm)\\Shield 02 Blue",
		equipType: EquipType.Shield,
		armor: 12,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 45,
		goldCost: 460,
		name: "shield03",
		resourceName: "skins\\04 Attach Weapons\\Shields (L Arm)\\Shield 02 Brown",
		equipType: EquipType.Shield,
		armor: 8,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 2,
		mDmg: 0,
		skill: [ SKILL_LIST[10]  ],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 46,
		goldCost: 390,
		name: "shield04",
		resourceName: "skins\\04 Attach Weapons\\Shields (L Arm)\\Shield 02 Green",
		equipType: EquipType.Shield,
		armor: 10,
		health: 14,
		dmg: 0,
		spd: 0,
		mArmor: 8,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 47,
		goldCost: 460,
		name: "shield05",
		resourceName: "skins\\04 Attach Weapons\\Shields (L Arm)\\Shield 02 Purple",
		equipType: EquipType.Shield,
		armor: 2,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 8,
		mDmg: 0,
		skill: [ SKILL_LIST[11]  ],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 48,
		goldCost: 100,
		name: "dagger02",
		resourceName: "skins\\04 Attach Weapons\\Daggers (R Arm)\\Dagger 01 Red",
		equipType: EquipType.Weapon_L,
		aniName: "Melee Left Attack 01",
		armor: 0,
		health: 0,
		dmg: 3,
		spd: -0.25,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 49,
		goldCost: 400,
		name: "dagger03",
		resourceName: "skins\\04 Attach Weapons\\Daggers (R Arm)\\Dagger 02 Blue",
		equipType: EquipType.Weapon_R,
		aniName: "Melee Right Attack 01",
		armor: 0,
		health: 0,
		dmg: 8,
		spd: -0.3,
		mArmor: 0,
		mDmg: 0,
		skill: [ SKILL_LIST[12]  ],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 50,
		goldCost: 380,
		name: "dagger04",
		resourceName: "skins\\04 Attach Weapons\\Daggers (R Arm)\\Dagger 02 Green",
		equipType: EquipType.Weapon_L,
		aniName: "Melee Left Attack 01",
		armor: 0,
		health: 0,
		dmg: 6,
		spd: -0.3,
		mArmor: 0,
		mDmg: 0,
		skill: [ SKILL_LIST[12]  ],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 51,
		goldCost: 1250,
		name: "wing01",
		resourceName: "skins\\03 Attach Accessories\\Wings (Back)\\Wings 01 White",
		equipType: EquipType.Back,
		aniName: "",
		armor: 2,
		health: 20,
		dmg: 0,
		spd: 0,
		mArmor: 2,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 52,
		goldCost: 1250,
		name: "wing02",
		resourceName: "skins\\03 Attach Accessories\\Wings (Back)\\Wings 01 Gold",
		equipType: EquipType.Back,
		aniName: "",
		armor: 2,
		health: 20,
		dmg: 0,
		spd: 0,
		mArmor: 2,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 53,
		goldCost: 1250,
		name: "wing03",
		resourceName: "skins\\03 Attach Accessories\\Wings (Back)\\Wings 01 Black",
		equipType: EquipType.Back,
		aniName: "",
		armor: 2,
		health: 20,
		dmg: 0,
		spd: 0,
		mArmor: 2,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 54,
		goldCost: 560,
		name: "longbow_sova",
		resourceName: "equip\\Sova\\SovaBow",
		equipType: EquipType.Bow,
		aniName: "Longbow Shoot Attack 01",
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0.4,
		mArmor: 2,
		boldID: 5,
		mDmg: 18,
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 55,
		goldCost: 750,
		name: "patreon_01",
		resourceName: "equip\\patreon\\patreon_belt01",
		equipType: EquipType.Patreon,
		aniName: "",
		armor: 2,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		boldID: 0,
		mDmg: 0,
		isPatreon: true,
		isEventItem: false
	},
	{
		id: 56,
		goldCost: 750,
		name: "patreon_02",
		resourceName: "equip\\patreon\\patreon_belt02",
		equipType: EquipType.Patreon,
		aniName: "",
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 2,
		boldID: 0,
		mDmg: 0,
		isPatreon: true,
		isEventItem: false
	},
	{
		id: 57,
		goldCost: 450,
		name: "shoes02",
		resourceName: "equip\\schuhe02\\Schuh01",
		equipType: EquipType.Shoes,
		armor: 4,
		health: 0,
		dmg: 1,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 58,
		goldCost: 500,
		name: "shoes03",
		resourceName: "equip\\schuhe03\\Schuh01",
		equipType: EquipType.Shoes,
		armor: 1,
		health: 40,
		dmg: 0,
		spd: 0,
		mArmor: 1,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 59,
		goldCost: 6666666,
		name: "hair09",
		resourceName: "skins\\02 Attach Hair\\Male\\Hair Male 17 Aqua",
		equipType: EquipType.Hair,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 60,
		goldCost: 750,
		name: "boss00_shoes",
		resourceName: "equip\\Skeleton\\skeleton_king_boots_",
		equipType: EquipType.Shoes,
		armor: 8,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: [ SKILL_LIST[18]  ],
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 61,
		goldCost: 750,
		name: "boss00_sword",
		resourceName: "equip\\Skeleton\\skeleton_king_sword",
		equipType: EquipType.Weapon_R,
		aniName: "Melee Right Attack 03",
		armor: 1,
		health: 0,
		dmg: 34,
		spd: 0.3,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 62,
		goldCost: 750,
		name: "boss00_hat",
		resourceName: "equip\\Skeleton\\skelet_hat",
		equipType: EquipType.HeadTop,
		armor: 12,
		health: 5,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 63,
		goldCost: 750,
		name: "boss00_face",
		resourceName: "equip\\Skeleton\\skelet_face",
		equipType: EquipType.HeadFront,
		armor: 4,
		health: 20,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: [ SKILL_LIST[16]  ],
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 64,
		goldCost: 750,
		name: "boss00_cape",
		resourceName: "equip\\Skeleton\\skelet_cape",
		equipType: EquipType.Back,
		aniName: "",
		armor: 2,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: [ SKILL_LIST[17]  ],
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 65,
		goldCost: 750,
		name: "boss00_patreon",
		resourceName: "equip\\Skeleton\\patreon_skeleton",
		equipType: EquipType.Patreon,
		aniName: "",
		armor: 1,
		health: 0,
		dmg: 1,
		spd: 0,
		mArmor: 0,
		boldID: 0,
		mDmg: 0,
		isPatreon: true,
		isEventItem: false
	},
	{
		id: 66,
		goldCost: 550,
		name: "xenobasher",
		resourceName: "equip\\XenoBasher\\xenobasher",
		equipType: EquipType.Weapon_R,
		aniName: "Melee Right Attack 03",
		armor: 0,
		health: 0,
		dmg: 21,
		spd: 0.15,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		skill: [ SKILL_LIST[19]  ],
		isEventItem: true
	},
	{
		id: 67,
		goldCost: 150,
		name: "boxing_glove_right",
		resourceName: "skins\\04 Attach Weapons\\Knuckles (Both Arms)\\Boxing_glove_B_right",
		equipType: EquipType.Weapon_R,
		aniName: "RightPunchAttack0",
		armor: 0,
		health: 5,
		dmg: 3,
		spd: -0.35,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 68,
		goldCost: 150,
		name: "boxing_glove_left",
		resourceName: "skins\\04 Attach Weapons\\Knuckles (Both Arms)\\Boxing_glove_B_left",
		equipType: EquipType.Weapon_L,
		aniName: "LeftPunchAttack1",
		armor: 0,
		health: 5,
		dmg: 3,
		spd: -0.35,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 69,
		goldCost: 500,
		name: "boxing_gloveA_right01",
		resourceName: "skins\\04 Attach Weapons\\Knuckles (Both Arms)\\Boxing_glove_A_right",
		equipType: EquipType.Weapon_R,
		aniName: "RightPunchAttack0",
		armor: 0,
		health: 12,
		dmg: 7,
		spd: -0.45,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 70,
		goldCost: 550,
		name: "boxing_gloveA_left01",
		resourceName: "skins\\04 Attach Weapons\\Knuckles (Both Arms)\\Boxing_glove_A_left",
		equipType: EquipType.Weapon_L,
		aniName: "LeftPunchAttack1",
		armor: 0,
		health: 12,
		dmg: 5,
		spd: -0.45,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false,
		skill: [ SKILL_LIST[20]  ]
	},
	{
		id: 71,
		goldCost: 650,
		name: "kriegsgleven",
		resourceName: "equip\\Kriegsgleven\\Kriegsgleven",
		equipType: EquipType.Weapon_R,
		aniName: "Melee Right Attack 03",
		armor: 1,
		health: 0,
		dmg: 17,
		spd: 0.1,
		mArmor: 1,
		mDmg: 0,
		isPatreon: false,
		isEventItem: true,
		skill: [
            SKILL_LIST[22],
			SKILL_LIST[23]
        ]
	},
	{
		id: 72,
		goldCost: 625,
		name: "thieve_black01",
		resourceName: "Male White Archer 01 light",
		equipType: EquipType.Armor,
		armor: 5,
		health: 60,
		dmg: 0,
		spd: -0.12,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 73,
		goldCost: 1150,
		name: "thieve_black02",
		resourceName: "Male White Archer 02 Olive",
		equipType: EquipType.Armor,
		armor: 9,
		health: 40,
		dmg: 0,
		spd: -0.15,
		mArmor: 1,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 74,
		goldCost: 1550,
		name: "thieve_black03",
		resourceName: "Male White Archer 03 Blue",
		equipType: EquipType.Armor,
		armor: 8,
		health: 55,
		dmg: 0,
		spd: -0.18,
		mArmor: 2,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 75,
		goldCost: 630,
		name: "knight02",
		resourceName: "Male White Knight 02 Blue",
		equipType: EquipType.Armor,
		armor: 15,
		health: 0,
		dmg: 0,
		spd: 0.05,
		mArmor: 1,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 76,
		goldCost: 1150,
		name: "knight03",
		resourceName: "Male White Knight 03 Blue",
		equipType: EquipType.Armor,
		armor: 18,
		health: 0,
		dmg: 0,
		spd: 0.07,
		mArmor: 4,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 77,
		goldCost: 1590,
		name: "knight04",
		resourceName: "Male White Knight 05 Red",
		equipType: EquipType.Armor,
		armor: 26,
		health: 30,
		dmg: 0,
		spd: 0.1,
		mArmor: 1,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 78,
		goldCost: 650,
		name: "barbarian02",
		resourceName: "Male White Barbarian 02 Green",
		equipType: EquipType.Armor,
		armor: 1,
		health: 45,
		dmg: 4,
		spd: 0,
		mArmor: 2,
		mDmg: 2,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 79,
		goldCost: 1100,
		name: "barbarian03",
		resourceName: "Male White Barbarian 05 Red",
		equipType: EquipType.Armor,
		armor: 2,
		health: 65,
		dmg: 5,
		spd: 0,
		mArmor: 2,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 80,
		goldCost: 1500,
		name: "barbarian04",
		resourceName: "Male White Barbarian 03 Brown",
		equipType: EquipType.Armor,
		armor: 2,
		health: 88,
		dmg: 6,
		spd: 0.05,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 81,
		goldCost: 650,
		name: "robe02",
		resourceName: "Male White L Robe 01 Green",
		equipType: EquipType.Armor,
		armor: 0,
		health: 4,
		dmg: 0,
		spd: -0.03,
		mArmor: 14,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 82,
		goldCost: 1125,
		name: "robe03",
		resourceName: "Male White L Robe 02 Red",
		equipType: EquipType.Armor,
		armor: 2,
		health: 15,
		dmg: 0,
		spd: -0.02,
		mArmor: 20,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 83,
		goldCost: 1700,
		name: "robe04",
		resourceName: "Male White Wizard 03 Blue",
		equipType: EquipType.Armor,
		armor: 2,
		health: 10,
		dmg: 0,
		spd: 0,
		mArmor: 30,
		mDmg: 2,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 84,
		goldCost: 800,
		name: "zombie_glove_right",
		resourceName: "equip\\boss02\\boss02_r_hand",
		equipType: EquipType.Weapon_R,
		aniName: "RightPunchAttack0",
		armor: 5,
		health: 0,
		dmg: 15,
		spd: -0.17,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: true,
		skill: [ SKILL_LIST[26]  ]
	},
	{
		id: 85,
		goldCost: 800,
		name: "zombie_glove_left",
		resourceName: "equip\\boss02\\boss02_l_hand",
		equipType: EquipType.Weapon_L,
		aniName: "LeftPunchAttack1",
		armor: 4,
		health: 0,
		dmg: 11,
		spd: -0.17,
		mArmor: 5,
		mDmg: 0,
		isPatreon: false,
		isEventItem: true,
		skill: [ SKILL_LIST[27]  ]
	},
	{
		id: 86,
		goldCost: 1400,
		name: "Klingenreste",
		resourceName: "equip\\boss02\\boss02_back",
		equipType: EquipType.Back,
		aniName: "",
		armor: 15,
		health: -40,
		dmg: 0,
		spd: 0,
		mArmor: 15,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 87,
		goldCost: 750,
		name: "boss02_patreon",
		resourceName: "equip\\boss02\\boss02_patreon",
		equipType: EquipType.Patreon,
		aniName: "",
		armor: 1,
		health: 0,
		dmg: 1,
		spd: 0,
		mArmor: 1,
		boldID: 0,
		mDmg: 1,
		isPatreon: true,
		isEventItem: false
	},
	{
		id: 88,
		goldCost: 850,
		name: "boss02_face",
		resourceName: "equip\\boss02\\boss02_face",
		equipType: EquipType.HeadFront,
		armor: 0,
		health: 26,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false,
		skill: [ SKILL_LIST[28]  ]
	},
	{
		id: 89,
		goldCost: 6666666,
		name: "hair10",
		resourceName: "skins\\02 Attach Hair\\Male\\Hair Male 17 Black",
		equipType: EquipType.Hair,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 90,
		goldCost: 6666666,
		name: "hair11",
		resourceName: "skins\\02 Attach Hair\\Male\\Hair Male 17 Red",
		equipType: EquipType.Hair,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 91,
		goldCost: 250,
		name: "hair12",
		resourceName: "skins\\02 Attach Hair\\Male\\Hair Male 02 Black",
		equipType: EquipType.Hair,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 92,
		goldCost: 250,
		name: "hair13",
		resourceName: "skins\\02 Attach Hair\\Male\\Hair Male 02 Blonde",
		equipType: EquipType.Hair,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 93,
		goldCost: 250,
		name: "hair14",
		resourceName: "skins\\02 Attach Hair\\Male\\Hair Male 02 Brown",
		equipType: EquipType.Hair,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 94,
		goldCost: 250,
		name: "hair15",
		resourceName: "skins\\02 Attach Hair\\Female\\Hair Female 02 Cyan",
		equipType: EquipType.Hair,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 95,
		goldCost: 250,
		name: "hair16",
		resourceName: "skins\\02 Attach Hair\\Male\\Hair Male 02 Purple",
		equipType: EquipType.Hair,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 96,
		goldCost: 250,
		name: "hair17",
		resourceName: "skins\\02 Attach Hair\\Male\\Hair Male 02 Red",
		equipType: EquipType.Hair,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 97,
		goldCost: 250,
		name: "hair18",
		resourceName: "skins\\02 Attach Hair\\Male\\Hair Male 02 Grey",
		equipType: EquipType.Hair,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 98,
		goldCost: 5000,
		name: "hair19",
		resourceName: "skins\\02 Attach Hair\\Male\\Hair Male 18 Black",
		equipType: EquipType.Hair,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 99,
		goldCost: 5000,
		name: "hair20",
		resourceName: "skins\\02 Attach Hair\\Male\\Hair Male 18 Purple",
		equipType: EquipType.Hair,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 100,
		goldCost: 1175,
		name: "tb_hammer",
		resourceName: "equip\\torbjorn\\tb_hammer",
		equipType: EquipType.Shield,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 101,
		goldCost: 1100,
		name: "groundedant",
		resourceName: "equip\\GAntHelm\\groundedAnt",
		equipType: EquipType.HeadTop,
		armor: 25,
		health: 0,
		dmg: 0,
		spd: 0.1,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: true,
		skill: [ SKILL_LIST[29]  ]
	},
	{
		id: 102,
		goldCost: 0,
		name: "pet01",
		resourceName: "pets\\cuteangelpurple",
		equipType: EquipType.Pet,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 103,
		goldCost: 0,
		name: "spooky",
		resourceName: "pets\\spooky",
		equipType: EquipType.Pet,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 104,
		goldCost: 750,
		name: "shoes04",
		resourceName: "equip\\schuhe04\\Schuh01",
		equipType: EquipType.Shoes,
		armor: 1,
		health: 0,
		dmg: 0,
		spd: -0.05,
		mArmor: 2,
		mDmg: 2,
		isPatreon: false,
		isEventItem: false,
		skill: [ SKILL_LIST[30]  ]
	},
	{
		id: 105,
		goldCost: 680,
		name: "shoes05",
		resourceName: "equip\\schuhe05\\Schuh01",
		equipType: EquipType.Shoes,
		armor: 3,
		health: 10,
		dmg: 0,
		spd: -0.3,
		mArmor: 2,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 106,
		goldCost: 1450,
		name: "wing04",
		resourceName: "skins\\03 Attach Accessories\\Wings (Back)\\Wings 03 BoneB",
		equipType: EquipType.Back,
		aniName: "",
		armor: 0,
		health: 15,
		dmg: 4,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 107,
		goldCost: 1450,
		name: "wing05",
		resourceName: "skins\\03 Attach Accessories\\Wings (Back)\\Wings 03 BoneBlue",
		equipType: EquipType.Back,
		aniName: "",
		armor: 0,
		health: 15,
		dmg: 4,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 108,
		goldCost: 1450,
		name: "wing06",
		resourceName: "skins\\03 Attach Accessories\\Wings (Back)\\Wings 03 BoneW",
		equipType: EquipType.Back,
		aniName: "",
		armor: 0,
		health: 15,
		dmg: 4,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 109,
		goldCost: 1550,
		name: "tesladem01",
		resourceName: "skins\\03 Attach Accessories\\Back Props (Back)\\Back Prop 01B",
		equipType: EquipType.Back,
		aniName: "",
		armor: 0,
		health: 0,
		dmg: 0,
		spd: -0.05,
		mArmor: 5,
		mDmg: 2,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 110,
		goldCost: 1550,
		name: "tesladem02",
		resourceName: "skins\\03 Attach Accessories\\Back Props (Back)\\Back Prop 01W",
		equipType: EquipType.Back,
		aniName: "",
		armor: 0,
		health: 0,
		dmg: 0,
		spd: -0.05,
		mArmor: 5,
		mDmg: 2,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 111,
		goldCost: 1550,
		name: "tesladem03",
		resourceName: "skins\\03 Attach Accessories\\Back Props (Back)\\Back Prop 01 Green",
		equipType: EquipType.Back,
		aniName: "",
		armor: 0,
		health: 0,
		dmg: 0,
		spd: -0.05,
		mArmor: 5,
		mDmg: 2,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 112,
		goldCost: 0,
		name: "devili",
		resourceName: "pets\\DragonSD_05",
		equipType: EquipType.Pet,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 113,
		goldCost: 1900,
		name: "wing07",
		resourceName: "skins\\03 Attach Accessories\\Wings (Back)\\Wings_Dragon_Elder",
		equipType: EquipType.Back,
		aniName: "",
		armor: 12,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 8,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 114,
		goldCost: 1900,
		name: "wing08",
		resourceName: "skins\\03 Attach Accessories\\Wings (Back)\\Wings_Dragon_Ice",
		equipType: EquipType.Back,
		aniName: "",
		armor: 8,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 12,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 115,
		goldCost: 1900,
		name: "wing09",
		resourceName: "skins\\03 Attach Accessories\\Wings (Back)\\Wings_Dragon_Orange",
		equipType: EquipType.Back,
		aniName: "",
		armor: 10,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 10,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 116,
		goldCost: 1750,
		name: "wing10",
		resourceName: "skins\\03 Attach Accessories\\Wings (Back)\\Wings_Butterfly_Light",
		equipType: EquipType.Back,
		aniName: "",
		armor: 0,
		health: 25,
		dmg: 0,
		spd: -0.25,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 117,
		goldCost: 1750,
		name: "wing11",
		resourceName: "skins\\03 Attach Accessories\\Wings (Back)\\Wings_Butterfly_Nature",
		equipType: EquipType.Back,
		aniName: "",
		armor: 0,
		health: 35,
		dmg: 0,
		spd: -0.05,
		mArmor: 0,
		mDmg: 0,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 118,
		goldCost: 1750,
		name: "wing12",
		resourceName: "skins\\03 Attach Accessories\\Wings (Back)\\Wings_Butterfly_Undead",
		equipType: EquipType.Back,
		aniName: "",
		armor: 0,
		health: -30,
		dmg: 2,
		spd: -0.4,
		mArmor: 0,
		mDmg: 2,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 119,
		goldCost: 2000,
		name: "thieve_black05",
		resourceName: "Male White Archer 05 Green",
		equipType: EquipType.Armor,
		armor: 10,
		health: 50,
		dmg: 0,
		spd: 0,
		mArmor: 3,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false,
		skill: [ SKILL_LIST[31]  ]
	},
	{
		id: 120,
		goldCost: 2000,
		name: "knight05",
		resourceName: "Male White Knight 06 Red",
		equipType: EquipType.Armor,
		armor: 35,
		health: 60,
		dmg: 0,
		spd: 0.2,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 121,
		goldCost: 2000,
		name: "barbarian05",
		resourceName: "Male White Barbarian 05 Green",
		equipType: EquipType.Armor,
		armor: 3,
		health: 92,
		dmg: 0,
		spd: 0,
		mArmor: 3,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false,
		skill: [ SKILL_LIST[32]  ]
	},
	{
		id: 122,
		goldCost: 2000,
		name: "robe05",
		resourceName: "Male White Wizard 04 Blue",
		equipType: EquipType.Armor,
		armor: 4,
		health: 20,
		dmg: 0,
		spd: 0.1,
		mArmor: 22,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false,
		skill: [ SKILL_LIST[33]  ]
	},
	{
		id: 123,
		goldCost: 0,
		name: "reddragon",
		resourceName: "pets\\reddragon",
		equipType: EquipType.Pet,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 124,
		goldCost: 1300,
		name: "dunkelschwert",
		resourceName: "equip\\darksword\\darksword",
		equipType: EquipType.Weapon_R,
		aniName: "Melee Right Attack 03",
		armor: 0,
		health: 0,
		dmg: 20,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: true,
		skill: [ SKILL_LIST[34]  ]
	},
	{
		id: 125,
		goldCost: 2050,
		name: "dagger05",
		resourceName: "equip\\new1502\\Dagger 03 Yellow",
		equipType: EquipType.Weapon_R,
		aniName: "Melee Left Attack 01",
		armor: 0,
		health: 0,
		dmg: 16,
		spd: -0.45,
		mArmor: 0,
		mDmg: 0,
		skill: [ SKILL_LIST[6]  ],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 126,
		goldCost: 2350,
		name: "dagger06",
		resourceName: "equip\\new1502\\Dagger_Beil",
		equipType: EquipType.Weapon_L,
		aniName: "Melee Left Attack 01",
		armor: 1,
		health: 0,
		dmg: 13,
		spd: -0.15,
		mArmor: 1,
		mDmg: 0,
		skill: [ SKILL_LIST[35]  ],
		isPatreon: false,
		isEventItem: false,
		desc: "Die Waffe eines Metzgers, welcher seit Jahren nicht nur Tiere damit erlegt."
	},
	{
		id: 127,
		goldCost: 1980,
		name: "longbow04",
		resourceName: "equip\\new1502\\Longbow 02 Black",
		equipType: EquipType.Bow,
		aniName: "Longbow Shoot Attack 01",
		armor: 0,
		health: 0,
		dmg: 15,
		spd: 0.55,
		mArmor: 0,
		mDmg: 0,
		boldID: 0,
		skill: [ SKILL_LIST[27]  ],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 128,
		goldCost: 2500,
		name: "longbow05",
		resourceName: "equip\\new1502\\Longbow 03 Magenta",
		equipType: EquipType.Bow,
		aniName: "Longbow Shoot Attack 01",
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 8,
		boldID: 8,
		skill: [ SKILL_LIST[5]  ],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 129,
		goldCost: 1220,
		name: "shield06",
		resourceName: "equip\\new1502\\Shield 05 Green",
		equipType: EquipType.Shield,
		armor: 8,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 3,
		mDmg: 0,
		skill: [ SKILL_LIST[30]  ],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 130,
		goldCost: 2150,
		name: "shield07",
		resourceName: "equip\\new1502\\Shield 06 Red",
		equipType: EquipType.Shield,
		armor: 20,
		health: 10,
		dmg: 0,
		spd: -0.1,
		mArmor: 18,
		mDmg: 0,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 131,
		goldCost: 2470,
		name: "shield08",
		resourceName: "equip\\new1502\\Shield 09 Green",
		equipType: EquipType.Shield,
		armor: 18,
		health: 25,
		dmg: 0,
		spd: 0.15,
		mArmor: 2,
		mDmg: 0,
		skill: [ SKILL_LIST[36]  ],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 132,
		goldCost: 2280,
		name: "eh_sword_tolaran",
		resourceName: "equip\\new1502\\Sword 05 Fire Ice",
		equipType: EquipType.Weapon_R,
		aniName: "Melee Right Attack 03",
		armor: 0,
		health: 0,
		dmg: 22,
		spd: 0.1,
		mArmor: 0,
		mDmg: 0,
		skill: [ SKILL_LIST[37]  ],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 133,
		goldCost: 2450,
		name: "eh_sword_baldan",
		resourceName: "equip\\new1502\\Sword 06 Purple",
		equipType: EquipType.Weapon_R,
		aniName: "Melee Right Attack 03",
		armor: 0,
		health: 0,
		dmg: 26,
		spd: 0.15,
		mArmor: 0,
		mDmg: 0,
		skill: [
            SKILL_LIST[10],
            SKILL_LIST[11]],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 134,
		goldCost: 2780,
		name: "eh_sword_doombomb",
		resourceName: "equip\\new1502\\Sword 09 Red",
		equipType: EquipType.Weapon_R,
		aniName: "Melee Right Attack 03",
		armor: 1,
		health: 0,
		dmg: 21,
		spd: 0.4,
		mArmor: 1,
		mDmg: 5,
		skill: [ SKILL_LIST[39]  ],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 135,
		goldCost: 2650,
		name: "incalibur",
		resourceName: "equip\\new1502\\Sword 10 Red Gold",
		equipType: EquipType.Weapon_R,
		aniName: "Melee Right Attack 03",
		armor: 2,
		health: 5,
		dmg: 42,
		spd: 0.25,
		mArmor: 0,
		mDmg: 0,
		skill: [ SKILL_LIST[20]  ],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 136,
		goldCost: 2425,
		name: "teslabold",
		resourceName: "equip\\new1502\\Wand 05 Green",
		equipType: EquipType.Wand,
		aniName: "Projectile Right Attack 01",
		armor: 0,
		health: 0,
		dmg: 0,
		spd: -0.1,
		mArmor: 0,
		mDmg: 17,
		boldID: 10,
		skill: undefined,
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 137,
		goldCost: 1825,
		name: "broomstick",
		resourceName: "equip\\new1502\\Wand 06 Broom Red",
		equipType: EquipType.Wand,
		aniName: "Projectile Right Attack 01",
		armor: 0,
		health: 0,
		dmg: 0,
		spd: -0.15,
		mArmor: 4,
		mDmg: 24,
		boldID: 1,
		skill: [ SKILL_LIST[22]  ],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 138,
		goldCost: 2385,
		name: "hemiosstab",
		resourceName: "equip\\new1502\\Wand 07 Green",
		equipType: EquipType.Wand,
		aniName: "Projectile Right Attack 01",
		armor: 0,
		health: 30,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 13,
		boldID: 3,
		skill: [ SKILL_LIST[40]  ],
		isPatreon: false,
		isEventItem: false
	},
	{
		id: 139,
		goldCost: 1650,
		name: "frostner",
		resourceName: "equip\\frostner\\frostner",
		equipType: EquipType.Weapon_R,
		aniName: "Melee Right Attack 03",
		armor: 4,
		health: 0,
		dmg: 48,
		spd: 0.65,
		mArmor: 0,
		mDmg: 5,
		isPatreon: false,
		isEventItem: true,
		skill: [ SKILL_LIST[3]  ]
	},
	{
		id: 140,
		goldCost: 1300,
		name: "vacudrone",
		resourceName: "equip\\VacuDrone\\VacuDrone",
		equipType: EquipType.Shield,
		armor: 0,
		health: 0,
		dmg: 2,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 141,
		goldCost: 0,
		name: "blackwhite",
		resourceName: "pets\\BlackAndWhite",
		equipType: EquipType.Pet,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 142,
		goldCost: 0,
		name: "Magmar",
		resourceName: "pets\\Magmar",
		equipType: EquipType.Pet,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 143,
		goldCost: 1760,
		name: "dimihat",
		resourceName: "equip\\resvillage\\DimiKopf",
		equipType: EquipType.HeadTop,
		armor: 6,
		health: 40,
		dmg: 1,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 144,
		goldCost: 2600,
		name: "dimiclaw",
		resourceName: "equip\\resvillage\\DimiKralle",
		equipType: EquipType.Weapon_R,
		aniName: "RightPunchAttack0",
		armor: 4,
		health: 0,
		dmg: 5,
		spd: 0.15,
		mArmor: 4,
		mDmg: 0,
		isPatreon: false,
		isEventItem: true,
		skill: [ SKILL_LIST[38]  ]
	},
	{
		id: 145,
		goldCost: 0,
		name: "toonreeperpet",
		resourceName: "pets\\ToonReeperPet",
		equipType: EquipType.Pet,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 146,
		goldCost: 1520,
		name: "daysgonebasi",
		resourceName: "equip\\DaysGone\\Basi",
		equipType: EquipType.Weapon_R,
		aniName: "Melee Right Attack 03",
		armor: 2,
		health: 0,
		dmg: 25,
		spd: -0.15,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: true,
		skill: [
            SKILL_LIST[20],
            SKILL_LIST[26]]
	},
	{
		id: 147,
		goldCost: 2050,
		name: "vipermask",
		resourceName: "equip\\ViperMask\\vmask",
		equipType: EquipType.HeadFront,
		armor: 10,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 10,
		mDmg: 5,
		isPatreon: false,
		isEventItem: true,
		skill: [ SKILL_LIST[41]  ]
	},
	{
		id: 148,
		goldCost: 0,
		name: "fireling",
		resourceName: "pets\\Fireling",
		equipType: EquipType.Pet,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 149,
		goldCost: 0,
		name: "goldenbee",
		resourceName: "pets\\goldbee",
		equipType: EquipType.Pet,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 150,
		goldCost: 0,
		name: "powerbee",
		resourceName: "pets\\powerbee",
		equipType: EquipType.Pet,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 151,
		goldCost: 0,
		name: "badspooky",
		resourceName: "pets\\spooky_bad",
		equipType: EquipType.Pet,
		armor: 0,
		health: 0,
		dmg: 0,
		spd: 0,
		mArmor: 0,
		mDmg: 0,
		isPatreon: false,
		isEventItem: true
	},
	{
		id: 152,
		goldCost: 2350,
		name: "swordofchaos",
		resourceName: "equip\\swordofchaos\\soc",
		equipType: EquipType.Weapon_R,
		aniName: "Melee Right Attack 03",
		armor: 5,
		health: 0,
		dmg: 28,
		spd: 0.4,
		mArmor: 5,
		mDmg: 0,
		skill: [ SKILL_LIST[32]  ],
		isPatreon: false,
		isEventItem: true
	}
];