/*
Array.from(document.querySelectorAll(".itemContainer")).map((x, i)=> {

    const name = x.querySelector(".itemName").innerText;
    const cmdName = x.querySelector(".itemInput").id;
    const img = x.querySelector(".itemPicture").src;
    const cost = x.querySelector(".itemCost").innerText;
    const life = x.querySelector(".itemSlotA").innerText.replace("p4", "");
    const speed = x.querySelector(".itemSlotB").innerText.replace("p5", "");
    const phyAtk = x.querySelector(".itemSlotC").innerText.replace("p6", "");
    
    const phyDef = x.querySelector(".itemSlotD").innerText.replace("p7", "");
    const mAtk = x.querySelector(".itemSlotE").innerText.replace("p8", "");
    const mDef = x.querySelector(".itemSlotC").innerText.replace("p9", "");

    return { 
        id: i, 
        aniName: name,
        name: cmdName,
        goldCoast: cost,
        health: life,
        spd: speed,
        dmg: phyAtk,
        armor: phyDef,
        mDmg: mAtk,
        mArmor: mDef
    };
})
*/



const ITEMSv2 =
    [
        {
            id: 0,
            aniName: "",
            name: "pet01",
            goldCost: 1700,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 1,
            aniName: "",
            name: "spooky",
            goldCost: 1700,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 2,
            aniName: "",
            name: "devili",
            goldCost: 1700,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 3,
            aniName: "",
            name: "reddragon",
            goldCost: 1700,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 4,
            aniName: "",
            name: "blackwhite",
            goldCost: 1700,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 5,
            aniName: "",
            name: "Magmar",
            goldCost: 1700,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 6,
            aniName: "",
            name: "toonreeperpet",
            goldCost: 1700,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 7,
            aniName: "",
            name: "fireling",
            goldCost: 1700,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 8,
            aniName: "",
            name: "goldenbee",
            goldCost: 1700,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 9,
            aniName: "",
            name: "powerbee",
            goldCost: 1700,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 10,
            aniName: "",
            name: "badspooky",
            goldCost: 1700,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 11,
            aniName: "",
            name: "jbat",
            goldCost: 1700,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 12,
            aniName: "",
            name: "bat",
            goldCost: 1700,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 13,
            aniName: "",
            name: "ebat",
            goldCost: 1700,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 14,
            aniName: "",
            name: "dagger01_blue",
            goldCost: 100,
            health: 0,
            spd: 2.5,
            dmg: 5,
            armor: 0,
            mDmg: 0,
            mArmor: 5
        },
        {
            id: 15,
            aniName: "",
            name: "eh_sword",
            goldCost: 175,
            health: 0,
            spd: -1.5,
            dmg: 9,
            armor: 0,
            mDmg: 0,
            mArmor: 9
        },
        {
            id: 16,
            aniName: "",
            name: "eh_sword01",
            goldCost: 320,
            health: 0,
            spd: -1.7,
            dmg: 15,
            armor: 0,
            mDmg: 0,
            mArmor: 15
        },
        {
            id: 17,
            aniName: "",
            name: "eh_sword02",
            goldCost: 360,
            health: 0,
            spd: -2,
            dmg: 12,
            armor: 0,
            mDmg: 0,
            mArmor: 12
        },
        {
            id: 18,
            aniName: "",
            name: "eh_sword03",
            goldCost: 360,
            health: 0,
            spd: -2,
            dmg: 13,
            armor: 0,
            mDmg: 0,
            mArmor: 13
        },
        {
            id: 19,
            aniName: "",
            name: "eh_sword04",
            goldCost: 420,
            health: 0,
            spd: -1.7,
            dmg: 9,
            armor: 0,
            mDmg: 0,
            mArmor: 9
        },
        {
            id: 20,
            aniName: "",
            name: "dagger03",
            goldCost: 400,
            health: 0,
            spd: 3,
            dmg: 8,
            armor: 0,
            mDmg: 0,
            mArmor: 8
        },
        {
            id: 21,
            aniName: "",
            name: "boss00_sword",
            goldCost: 750,
            health: 0,
            spd: -3,
            dmg: 34,
            armor: 1,
            mDmg: 0,
            mArmor: 34
        },
        {
            id: 22,
            aniName: "",
            name: "xenobasher",
            goldCost: 550,
            health: 0,
            spd: -1.5,
            dmg: 21,
            armor: 0,
            mDmg: 0,
            mArmor: 21
        },
        {
            id: 23,
            aniName: "",
            name: "boxing_glove_right",
            goldCost: 150,
            health: 5,
            spd: 3.5,
            dmg: 3,
            armor: 0,
            mDmg: 0,
            mArmor: 3
        },
        {
            id: 24,
            aniName: "",
            name: "boxing_gloveA_right01",
            goldCost: 500,
            health: 12,
            spd: 4.5,
            dmg: 7,
            armor: 0,
            mDmg: 0,
            mArmor: 7
        },
        {
            id: 25,
            aniName: "",
            name: "kriegsgleven",
            goldCost: 650,
            health: 0,
            spd: -1,
            dmg: 17,
            armor: 1,
            mDmg: 0,
            mArmor: 17
        },
        {
            id: 26,
            aniName: "",
            name: "zombie_glove_right",
            goldCost: 800,
            health: 0,
            spd: 1.7,
            dmg: 15,
            armor: 5,
            mDmg: 0,
            mArmor: 15
        },
        {
            id: 27,
            aniName: "",
            name: "dunkelschwert",
            goldCost: 1300,
            health: 0,
            spd: 0,
            dmg: 20,
            armor: 0,
            mDmg: 0,
            mArmor: 20
        },
        {
            id: 28,
            aniName: "",
            name: "dagger05",
            goldCost: 2050,
            health: 0,
            spd: 4.5,
            dmg: 16,
            armor: 0,
            mDmg: 0,
            mArmor: 16
        },
        {
            id: 29,
            aniName: "",
            name: "eh_sword_tolaran",
            goldCost: 2280,
            health: 0,
            spd: -1,
            dmg: 22,
            armor: 0,
            mDmg: 0,
            mArmor: 22
        },
        {
            id: 30,
            aniName: "",
            name: "eh_sword_baldan",
            goldCost: 2450,
            health: 0,
            spd: -1.5,
            dmg: 26,
            armor: 0,
            mDmg: 0,
            mArmor: 26
        },
        {
            id: 31,
            aniName: "",
            name: "eh_sword_doombomb",
            goldCost: 2780,
            health: 0,
            spd: -4,
            dmg: 21,
            armor: 1,
            mDmg: 5,
            mArmor: 21
        },
        {
            id: 32,
            aniName: "",
            name: "incalibur",
            goldCost: 2650,
            health: 5,
            spd: -2.5,
            dmg: 42,
            armor: 2,
            mDmg: 0,
            mArmor: 42
        },
        {
            id: 33,
            aniName: "",
            name: "frostner",
            goldCost: 1650,
            health: 0,
            spd: -6.5,
            dmg: 48,
            armor: 4,
            mDmg: 5,
            mArmor: 48
        },
        {
            id: 34,
            aniName: "",
            name: "dimiclaw",
            goldCost: 2600,
            health: 0,
            spd: -1.5,
            dmg: 8,
            armor: 5,
            mDmg: 0,
            mArmor: 8
        },
        {
            id: 35,
            aniName: "",
            name: "daysgonebasi",
            goldCost: 1520,
            health: 0,
            spd: 1.5,
            dmg: 25,
            armor: 2,
            mDmg: 0,
            mArmor: 25
        },
        {
            id: 36,
            aniName: "",
            name: "swordofchaos",
            goldCost: 2350,
            health: 0,
            spd: -4,
            dmg: 28,
            armor: 5,
            mDmg: 0,
            mArmor: 28
        },
        {
            id: 37,
            aniName: "",
            name: "anubis_schwert",
            goldCost: 2680,
            health: 0,
            spd: 0,
            dmg: 25,
            armor: 0,
            mDmg: 0,
            mArmor: 25
        },
        {
            id: 38,
            aniName: "",
            name: "dagger02",
            goldCost: 100,
            health: 0,
            spd: 2.5,
            dmg: 3,
            armor: 0,
            mDmg: 0,
            mArmor: 3
        },
        {
            id: 39,
            aniName: "",
            name: "dagger04",
            goldCost: 380,
            health: 0,
            spd: 3,
            dmg: 6,
            armor: 0,
            mDmg: 0,
            mArmor: 6
        },
        {
            id: 40,
            aniName: "",
            name: "boxing_glove_left",
            goldCost: 150,
            health: 5,
            spd: 3.5,
            dmg: 3,
            armor: 0,
            mDmg: 0,
            mArmor: 3
        },
        {
            id: 41,
            aniName: "",
            name: "boxing_gloveA_left01",
            goldCost: 550,
            health: 12,
            spd: 4.5,
            dmg: 5,
            armor: 0,
            mDmg: 0,
            mArmor: 5
        },
        {
            id: 42,
            aniName: "",
            name: "zombie_glove_left",
            goldCost: 800,
            health: 0,
            spd: 1.7,
            dmg: 11,
            armor: 4,
            mDmg: 0,
            mArmor: 11
        },
        {
            id: 43,
            aniName: "",
            name: "dagger06",
            goldCost: 2350,
            health: 0,
            spd: 1.5,
            dmg: 13,
            armor: 1,
            mDmg: 0,
            mArmor: 13
        },
        {
            id: 44,
            aniName: "",
            name: "anubis_schwert_klein",
            goldCost: 2280,
            health: 0,
            spd: 2,
            dmg: 22,
            armor: 0,
            mDmg: 0,
            mArmor: 22
        },
        {
            id: 45,
            aniName: "",
            name: "wand01",
            goldCost: 145,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 5,
            mArmor: 0
        },
        {
            id: 46,
            aniName: "",
            name: "wand02",
            goldCost: 310,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 10,
            mArmor: 0
        },
        {
            id: 47,
            aniName: "",
            name: "wand03",
            goldCost: 480,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 7,
            mArmor: 0
        },
        {
            id: 48,
            aniName: "",
            name: "wand04",
            goldCost: 450,
            health: 4,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 6,
            mArmor: 0
        },
        {
            id: 49,
            aniName: "",
            name: "wand05",
            goldCost: 450,
            health: 0,
            spd: -9.5,
            dmg: 0,
            armor: 0,
            mDmg: 32,
            mArmor: 0
        },
        {
            id: 50,
            aniName: "",
            name: "teslabold",
            goldCost: 2425,
            health: 0,
            spd: 1,
            dmg: 0,
            armor: 0,
            mDmg: 15,
            mArmor: 0
        },
        {
            id: 51,
            aniName: "",
            name: "broomstick",
            goldCost: 1825,
            health: 0,
            spd: 1.5,
            dmg: 0,
            armor: 0,
            mDmg: 23,
            mArmor: 0
        },
        {
            id: 52,
            aniName: "",
            name: "hemiosstab",
            goldCost: 2385,
            health: 30,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 13,
            mArmor: 0
        },
        {
            id: 53,
            aniName: "",
            name: "longbow_black",
            goldCost: 135,
            health: 0,
            spd: -5,
            dmg: 3,
            armor: 0,
            mDmg: 0,
            mArmor: 3
        },
        {
            id: 54,
            aniName: "",
            name: "longbow01",
            goldCost: 300,
            health: 0,
            spd: -4.5,
            dmg: 6,
            armor: 0,
            mDmg: 0,
            mArmor: 6
        },
        {
            id: 55,
            aniName: "",
            name: "longbow02",
            goldCost: 350,
            health: 0,
            spd: -5.5,
            dmg: 5,
            armor: 0,
            mDmg: 0,
            mArmor: 5
        },
        {
            id: 56,
            aniName: "",
            name: "longbow03",
            goldCost: 380,
            health: 0,
            spd: -4.5,
            dmg: 4,
            armor: 0,
            mDmg: 0,
            mArmor: 4
        },
        {
            id: 57,
            aniName: "",
            name: "longbow_sova",
            goldCost: 560,
            health: 0,
            spd: -4,
            dmg: 0,
            armor: 0,
            mDmg: 17,
            mArmor: 0
        },
        {
            id: 58,
            aniName: "",
            name: "longbow04",
            goldCost: 1980,
            health: 0,
            spd: -5.5,
            dmg: 14,
            armor: 0,
            mDmg: 0,
            mArmor: 14
        },
        {
            id: 59,
            aniName: "",
            name: "longbow05",
            goldCost: 2500,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 8,
            mArmor: 0
        },
        {
            id: 60,
            aniName: "",
            name: "shield01",
            goldCost: 170,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 5,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 61,
            aniName: "",
            name: "shield02",
            goldCost: 350,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 12,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 62,
            aniName: "",
            name: "shield03",
            goldCost: 460,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 8,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 63,
            aniName: "",
            name: "shield04",
            goldCost: 390,
            health: 14,
            spd: 0,
            dmg: 0,
            armor: 10,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 64,
            aniName: "",
            name: "shield05",
            goldCost: 460,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 2,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 65,
            aniName: "",
            name: "tb_hammer",
            goldCost: 1175,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 66,
            aniName: "",
            name: "shield06",
            goldCost: 1220,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 8,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 67,
            aniName: "",
            name: "shield07",
            goldCost: 2150,
            health: 10,
            spd: 1,
            dmg: 0,
            armor: 20,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 68,
            aniName: "",
            name: "shield08",
            goldCost: 2470,
            health: 30,
            spd: -1.5,
            dmg: 0,
            armor: 18,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 69,
            aniName: "",
            name: "vacudrone",
            goldCost: 1300,
            health: 0,
            spd: 0,
            dmg: 2,
            armor: 0,
            mDmg: 0,
            mArmor: 2
        },
        {
            id: 70,
            aniName: "",
            name: "batpumpkin",
            goldCost: 2000,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 2,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 71,
            aniName: "",
            name: "hat01_red",
            goldCost: 110,
            health: 4,
            spd: 0,
            dmg: 0,
            armor: 2,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 72,
            aniName: "",
            name: "headband01",
            goldCost: 125,
            health: 0,
            spd: 0,
            dmg: 1,
            armor: 3,
            mDmg: 0,
            mArmor: 1
        },
        {
            id: 73,
            aniName: "",
            name: "headband02",
            goldCost: 125,
            health: 0,
            spd: 0,
            dmg: 1,
            armor: 3,
            mDmg: 0,
            mArmor: 1
        },
        {
            id: 74,
            aniName: "",
            name: "headband03",
            goldCost: 155,
            health: 10,
            spd: 1,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 75,
            aniName: "",
            name: "headband04",
            goldCost: 275,
            health: 5,
            spd: 0,
            dmg: 0,
            armor: 2,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 76,
            aniName: "",
            name: "headband05",
            goldCost: 260,
            health: 0,
            spd: 1.5,
            dmg: 3,
            armor: 0,
            mDmg: 0,
            mArmor: 3
        },
        {
            id: 77,
            aniName: "",
            name: "event_egg01",
            goldCost: 335,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 6,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 78,
            aniName: "",
            name: "boss00_hat",
            goldCost: 750,
            health: 5,
            spd: 0,
            dmg: 0,
            armor: 12,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 79,
            aniName: "",
            name: "groundedant",
            goldCost: 1100,
            health: 0,
            spd: -1,
            dmg: 0,
            armor: 25,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 80,
            aniName: "",
            name: "dimihat",
            goldCost: 1760,
            health: 40,
            spd: 0,
            dmg: 1,
            armor: 6,
            mDmg: 0,
            mArmor: 1
        },
        {
            id: 81,
            aniName: "",
            name: "anubis_hat",
            goldCost: 2570,
            health: -12,
            spd: 3.5,
            dmg: 0,
            armor: 8,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 82,
            aniName: "",
            name: "face01_normal",
            goldCost: 140,
            health: 6,
            spd: 0,
            dmg: 2,
            armor: 1,
            mDmg: 0,
            mArmor: 2
        },
        {
            id: 83,
            aniName: "",
            name: "face01_red",
            goldCost: 200,
            health: 6,
            spd: 0,
            dmg: 2,
            armor: 2,
            mDmg: 4,
            mArmor: 2
        },
        {
            id: 84,
            aniName: "",
            name: "face01_black",
            goldCost: 200,
            health: 6,
            spd: 0,
            dmg: 6,
            armor: 2,
            mDmg: 0,
            mArmor: 6
        },
        {
            id: 85,
            aniName: "",
            name: "boss00_face",
            goldCost: 750,
            health: 20,
            spd: 0,
            dmg: 0,
            armor: 4,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 86,
            aniName: "",
            name: "boss02_face",
            goldCost: 850,
            health: 26,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 87,
            aniName: "",
            name: "vipermask",
            goldCost: 2050,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 10,
            mDmg: 5,
            mArmor: 0
        },
        {
            id: 88,
            aniName: "",
            name: "anubis_mask",
            goldCost: 2000,
            health: -15,
            spd: 0,
            dmg: 0,
            armor: 15,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 89,
            aniName: "",
            name: "thieve_black",
            goldCost: 150,
            health: 10,
            spd: 0.5,
            dmg: 0,
            armor: 3,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 90,
            aniName: "",
            name: "knight01",
            goldCost: 150,
            health: 0,
            spd: -0.5,
            dmg: 0,
            armor: 6,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 91,
            aniName: "",
            name: "barbarian01",
            goldCost: 150,
            health: 12,
            spd: 0,
            dmg: 1,
            armor: 0,
            mDmg: 0,
            mArmor: 1
        },
        {
            id: 92,
            aniName: "",
            name: "robe01",
            goldCost: 150,
            health: 2,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 93,
            aniName: "",
            name: "thieve_black01",
            goldCost: 625,
            health: 60,
            spd: 1.2,
            dmg: 0,
            armor: 5,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 94,
            aniName: "",
            name: "thieve_black02",
            goldCost: 1150,
            health: 40,
            spd: 1.5,
            dmg: 0,
            armor: 9,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 95,
            aniName: "",
            name: "thieve_black03",
            goldCost: 1550,
            health: 55,
            spd: 1.8,
            dmg: 0,
            armor: 8,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 96,
            aniName: "",
            name: "knight02",
            goldCost: 630,
            health: 0,
            spd: -0.5,
            dmg: 0,
            armor: 15,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 97,
            aniName: "",
            name: "knight03",
            goldCost: 1150,
            health: 0,
            spd: -0.7,
            dmg: 0,
            armor: 18,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 98,
            aniName: "",
            name: "knight04",
            goldCost: 1590,
            health: 30,
            spd: -1,
            dmg: 0,
            armor: 26,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 99,
            aniName: "",
            name: "barbarian02",
            goldCost: 650,
            health: 45,
            spd: 0,
            dmg: 4,
            armor: 1,
            mDmg: 2,
            mArmor: 4
        },
        {
            id: 100,
            aniName: "",
            name: "barbarian03",
            goldCost: 1100,
            health: 65,
            spd: 0,
            dmg: 5,
            armor: 2,
            mDmg: 0,
            mArmor: 5
        },
        {
            id: 101,
            aniName: "",
            name: "barbarian04",
            goldCost: 1500,
            health: 88,
            spd: -0.5,
            dmg: 6,
            armor: 2,
            mDmg: 0,
            mArmor: 6
        },
        {
            id: 102,
            aniName: "",
            name: "robe02",
            goldCost: 650,
            health: 4,
            spd: 0.3,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 103,
            aniName: "",
            name: "robe03",
            goldCost: 1125,
            health: 15,
            spd: 0.2,
            dmg: 0,
            armor: 2,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 104,
            aniName: "",
            name: "robe04",
            goldCost: 1700,
            health: 10,
            spd: 0,
            dmg: 0,
            armor: 2,
            mDmg: 2,
            mArmor: 0
        },
        {
            id: 105,
            aniName: "",
            name: "thieve_black05",
            goldCost: 2000,
            health: 50,
            spd: 0,
            dmg: 0,
            armor: 10,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 106,
            aniName: "",
            name: "knight05",
            goldCost: 2000,
            health: 60,
            spd: -2,
            dmg: 0,
            armor: 35,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 107,
            aniName: "",
            name: "barbarian05",
            goldCost: 2000,
            health: 92,
            spd: 0,
            dmg: 0,
            armor: 3,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 108,
            aniName: "",
            name: "robe05",
            goldCost: 2000,
            health: 20,
            spd: -1,
            dmg: 0,
            armor: 4,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 109,
            aniName: "",
            name: "wing01",
            goldCost: 1250,
            health: 20,
            spd: 0,
            dmg: 0,
            armor: 2,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 110,
            aniName: "",
            name: "wing02",
            goldCost: 1250,
            health: 20,
            spd: 0,
            dmg: 0,
            armor: 2,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 111,
            aniName: "",
            name: "wing03",
            goldCost: 1250,
            health: 20,
            spd: 0,
            dmg: 0,
            armor: 2,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 112,
            aniName: "",
            name: "boss00_cape",
            goldCost: 750,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 2,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 113,
            aniName: "",
            name: "Klingenreste",
            goldCost: 1400,
            health: -30,
            spd: 0,
            dmg: 0,
            armor: 15,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 114,
            aniName: "",
            name: "wing04",
            goldCost: 1450,
            health: 15,
            spd: 0,
            dmg: 4,
            armor: 0,
            mDmg: 0,
            mArmor: 4
        },
        {
            id: 115,
            aniName: "",
            name: "wing05",
            goldCost: 1450,
            health: 15,
            spd: 0,
            dmg: 4,
            armor: 0,
            mDmg: 0,
            mArmor: 4
        },
        {
            id: 116,
            aniName: "",
            name: "wing06",
            goldCost: 1450,
            health: 15,
            spd: 0,
            dmg: 4,
            armor: 0,
            mDmg: 0,
            mArmor: 4
        },
        {
            id: 117,
            aniName: "",
            name: "tesladem01",
            goldCost: 1550,
            health: 0,
            spd: 0.5,
            dmg: 0,
            armor: 0,
            mDmg: 2,
            mArmor: 0
        },
        {
            id: 118,
            aniName: "",
            name: "tesladem02",
            goldCost: 1550,
            health: 0,
            spd: 0.5,
            dmg: 0,
            armor: 0,
            mDmg: 2,
            mArmor: 0
        },
        {
            id: 119,
            aniName: "",
            name: "tesladem03",
            goldCost: 1550,
            health: 0,
            spd: 0.5,
            dmg: 0,
            armor: 0,
            mDmg: 2,
            mArmor: 0
        },
        {
            id: 120,
            aniName: "",
            name: "wing07",
            goldCost: 1900,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 12,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 121,
            aniName: "",
            name: "wing08",
            goldCost: 1900,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 8,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 122,
            aniName: "",
            name: "wing09",
            goldCost: 1900,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 10,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 123,
            aniName: "",
            name: "wing10",
            goldCost: 1750,
            health: 25,
            spd: 2.5,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 124,
            aniName: "",
            name: "wing11",
            goldCost: 1750,
            health: 35,
            spd: 0.5,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 125,
            aniName: "",
            name: "wing12",
            goldCost: 1750,
            health: -30,
            spd: 4,
            dmg: 2,
            armor: 0,
            mDmg: 2,
            mArmor: 2
        },
        {
            id: 126,
            aniName: "",
            name: "anubis_schulterarmor",
            goldCost: 2650,
            health: -5,
            spd: 1.5,
            dmg: 0,
            armor: 5,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 127,
            aniName: "",
            name: "eastertale",
            goldCost: 2600,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 128,
            aniName: "",
            name: "shoes01",
            goldCost: 100,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 2,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 129,
            aniName: "",
            name: "shoes02",
            goldCost: 450,
            health: 0,
            spd: 0,
            dmg: 1,
            armor: 4,
            mDmg: 0,
            mArmor: 1
        },
        {
            id: 130,
            aniName: "",
            name: "shoes03",
            goldCost: 500,
            health: 40,
            spd: 0,
            dmg: 0,
            armor: 1,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 131,
            aniName: "",
            name: "boss00_shoes",
            goldCost: 750,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 8,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 132,
            aniName: "",
            name: "shoes04",
            goldCost: 750,
            health: 0,
            spd: 0.5,
            dmg: 0,
            armor: 1,
            mDmg: 2,
            mArmor: 0
        },
        {
            id: 133,
            aniName: "",
            name: "shoes05",
            goldCost: 680,
            health: 10,
            spd: 3,
            dmg: 0,
            armor: 3,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 134,
            aniName: "",
            name: "skin_white",
            goldCost: 0,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 135,
            aniName: "",
            name: "skin_brown",
            goldCost: 0,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 136,
            aniName: "",
            name: "skin_black",
            goldCost: 0,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 137,
            aniName: "",
            name: "hair01",
            goldCost: 50,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 138,
            aniName: "",
            name: "hair02",
            goldCost: 50,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 139,
            aniName: "",
            name: "hair03",
            goldCost: 50,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 140,
            aniName: "",
            name: "hair04",
            goldCost: 50,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 141,
            aniName: "",
            name: "hair05",
            goldCost: 50,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 142,
            aniName: "",
            name: "hair06",
            goldCost: 50,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 143,
            aniName: "",
            name: "hair07",
            goldCost: 50,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 144,
            aniName: "",
            name: "hair08",
            goldCost: 6666666,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 145,
            aniName: "",
            name: "hair09",
            goldCost: 6666666,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 146,
            aniName: "",
            name: "hair10",
            goldCost: 6666666,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 147,
            aniName: "",
            name: "hair11",
            goldCost: 6666666,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 148,
            aniName: "",
            name: "hair12",
            goldCost: 250,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 149,
            aniName: "",
            name: "hair13",
            goldCost: 250,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 150,
            aniName: "",
            name: "hair14",
            goldCost: 250,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 151,
            aniName: "",
            name: "hair15",
            goldCost: 250,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 152,
            aniName: "",
            name: "hair16",
            goldCost: 250,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 153,
            aniName: "",
            name: "hair17",
            goldCost: 250,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 154,
            aniName: "",
            name: "hair18",
            goldCost: 250,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 155,
            aniName: "",
            name: "hair19",
            goldCost: 5000,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg: 0,
            mArmor: 0
        },
        {
            id: 156,
            aniName: "",
            name: "hair20",
            goldCost: 5000,
            health: 0,
            spd: 0,
            dmg: 0,
            armor: 0,
            mDmg:0,
            mArmor:0
        }
    ]