import SkillAttribute from "./skillAttributes"
import SkillType from "./skillType"


export type Skill = {
    ID: number,
    type: SkillType,
    attribute: SkillAttribute,
    Delay: number,
    Value: number,
    Icon: string
}

export const SKILL_LIST: Skill[] = [
	{
		ID: 0,
		type: SkillType.Passiv,
		attribute: SkillAttribute.SelfHeal,
		Delay: 1,
		Value: 3,
		Icon: "sprite\\self_heal",
	},
	{
		ID: 1,
		type: SkillType.AttackPassiv,
		attribute: SkillAttribute.ArmorPierce,
		Delay: 0.0,
		Value: 2,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 2,
		type: SkillType.AttackPassiv,
		attribute: SkillAttribute.Poison,
		Delay: 5,
		Value: 3,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 3,
		type: SkillType.AttackPassiv,
		attribute: SkillAttribute.Freeze,
		Delay: 2,
		Value: 0.75,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 4,
		type: SkillType.AttackSelf,
		attribute: SkillAttribute.DmgStack,
		Delay: 0.0,
		Value: 1,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 5,
		type: SkillType.AttackPassiv,
		attribute: SkillAttribute.Verwurzeln,
		Delay: 0.45,
		Value: 0.0,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 6,
		type: SkillType.AttackSelf,
		attribute: SkillAttribute.DoppelAttack,
		Delay: 0.0,
		Value: 0.0,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 7,
		type: SkillType.AttackPassiv,
		attribute: SkillAttribute.DamageDrain,
		Delay: 0.0,
		Value: 0.05,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 8,
		type: SkillType.AttackPassiv,
		attribute: SkillAttribute.ArmorDrain,
		Delay: 0.0,
		Value: 0.05,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 9,
		type: SkillType.AttackPassivAlly,
		attribute: SkillAttribute.Heal,
		Delay: 0.0,
		Value: 5,
		Icon: "sprite\\other_heal",
	},
	{
		ID: 10,
		type: SkillType.AttackedSelf,
		attribute: SkillAttribute.DmgReflect,
		Delay: 0.0,
		Value: 5,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 11,
		type: SkillType.AttackedSelf,
		attribute: SkillAttribute.MDmgReflect,
		Delay: 0.0,
		Value: 5,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 12,
		type: SkillType.AttackPassiv,
		attribute: SkillAttribute.ArmorPierce,
		Delay: 0.0,
		Value: 1,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 13,
		type: SkillType.AttackedSelf,
		attribute: SkillAttribute.DmgReflect,
		Delay: 5,
		Value: 20.0,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 14,
		type: SkillType.AttackedSelf,
		attribute: SkillAttribute.MDmgReflect,
		Delay: 5,
		Value: 20.0,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 15,
		type: SkillType.AttackPassiv,
		attribute: SkillAttribute.KnockBack,
		Delay: 0.0,
		Value: 4,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 16,
		type: SkillType.AttackPassiv,
		attribute: SkillAttribute.ArmorPierce,
		Delay: 0.0,
		Value: 3,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 17,
		type: SkillType.Passiv,
		attribute: SkillAttribute.MagImun,
		Delay: 0.0,
		Value: 4,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 18,
		type: SkillType.AttackPassiv,
		attribute: SkillAttribute.KnockBack,
		Delay: 0.0,
		Value: 1.5,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 19,
		type: SkillType.AttackPassiv,
		attribute: SkillAttribute.KnockBack,
		Delay: 0.0,
		Value: 0.75,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 20,
		type: SkillType.AttackPassiv,
		attribute: SkillAttribute.KnockOut,
		Delay: 0.3,
		Value: 0.0,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 21,
		type: SkillType.AttackPassiv,
		attribute: SkillAttribute.Absorbation,
		Delay: 0.0,
		Value: 0.07,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 22,
		type: SkillType.Passiv,
		attribute: SkillAttribute.Parrieren,
		Delay: 0.0,
		Value: 30.0,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 23,
		type: SkillType.AttackPassiv,
		attribute: SkillAttribute.Absorbation,
		Delay: 0.0,
		Value: 0.05,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 24,
		type: SkillType.AttackPassiv,
		attribute: SkillAttribute.Absorbation,
		Delay: 0.0,
		Value: 0.05,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 25,
		type: SkillType.AttackPassiv,
		attribute: SkillAttribute.Absorbation,
		Delay: 0.0,
		Value: 0.05,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 26,
		type: SkillType.AttackPassiv,
		attribute: SkillAttribute.Crit,
		Delay: 0.0,
		Value: 0.0,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 27,
		type: SkillType.AttackPassiv,
		attribute: SkillAttribute.faulnis,
		Delay: 2,
		Value: 0.0,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 28,
		type: SkillType.AttackedSelf,
		attribute: SkillAttribute.fear,
		Delay: 2.5,
		Value: 0.0,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 29,
		type: SkillType.PassivStats,
		attribute: SkillAttribute.ArmorIncreaseHealth,
		Delay: 0.0,
		Value: 2,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 30,
		type: SkillType.Passiv,
		attribute: SkillAttribute.SelfHeal,
		Delay: 1,
		Value: 2,
		Icon: "sprite\\self_heal",
	},
	{
		ID: 31,
		type: SkillType.Passiv,
		attribute: SkillAttribute.Parrieren,
		Delay: 0.0,
		Value: 33,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 32,
		type: SkillType.AttackedSelf,
		attribute: SkillAttribute.RageMode,
		Delay: 3,
		Value: 25,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 33,
		type: SkillType.AttackedSelf,
		attribute: SkillAttribute.Teleport,
		Delay: 0.0,
		Value: 40.0,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 34,
		type: SkillType.AttackPassiv,
		attribute: SkillAttribute.ArmorIgnore,
		Delay: 0.0,
		Value: 0.0,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 35,
		type: SkillType.AttackPassiv,
		attribute: SkillAttribute.Behead,
		Delay: 0.0,
		Value: 20.0,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 36,
		type: SkillType.Passiv,
		attribute: SkillAttribute.Parrieren,
		Delay: 0.0,
		Value: 35,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 37,
		type: SkillType.AttackPassiv,
		attribute: SkillAttribute.AdditionDamagePerEnemy,
		Delay: 0.0,
		Value: 5,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 38,
		type: SkillType.AttackPassiv,
		attribute: SkillAttribute.MultiDamage,
		Delay: 0.0,
		Value: 5,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 39,
		type: SkillType.AttackPassiv,
		attribute: SkillAttribute.Impact,
		Delay: 0.0,
		Value: 6,
		Icon: "sprite\\SkillIconTemplate",
	},
	{
		ID: 40,
		type: SkillType.AttackPassivAlly,
		attribute: SkillAttribute.Heal,
		Delay: 0.0,
		Value: 15,
		Icon: "sprite\\other_heal",
	},
	{
		ID: 41,
		type: SkillType.Passiv,
		attribute: SkillAttribute.VenomDust,
		Delay: 1,
		Value: 3,
		Icon: "sprite\\venom_dust",
	}
];

